"""VAPT-AI v3.2 baseline — 24 new tables (18 W1-C + 6 W1-D)

Creates all VAPT-AI-specific tables (prefixed with vapt_) + pgvector + pgcrypto
extensions. Does NOT touch legacy EVVO tables (users, scans, findings, ...)
which are still in use by 482 tests — those are filtered out by alembic/env.py
include_object().

Tables created (in FK dependency order):
     1. vapt_users
     2. vapt_refresh_tokens
     3. vapt_scans
     4. vapt_consent_forms
     5. vapt_assets
     6. vapt_pentest_facts
     7. vapt_findings
     8. vapt_evidence
     9. vapt_poc_results
    10. vapt_c2_sessions
    11. vapt_c2_tasks
    12. vapt_hitl_approvals
    13. vapt_audit_log
    14. vapt_quarantine
    15. vapt_attack_chains
    16. vapt_retest_requests
    17. vapt_wstg_methodology_catalog
    18. vapt_skill_executions
    19. vapt_kg_nodes
    20. vapt_kg_edges
    21. vapt_kg_scan_snapshots
    22. vapt_replay_traces
    23. vapt_rl_checkpoints
    24. vapt_rl_transitions

Extensions:
    - pgvector (for RAG / LightRAG vector storage)
    - pgcrypto (for gen_random_uuid() — built-in PG13+, but explicit for safety)

Revision ID: 0003_vapt_ai_baseline
Revises: 0002
Create Date: 2026-08-30

Generated by: /home/z/my-project/scripts/w1e_generate_migration.py
DO NOT EDIT MANUALLY — regenerate from models if schema changes.
"""
from __future__ import annotations

from alembic import op


revision = "0003_vapt_ai_baseline"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ---------- Extensions ----------
    # pgvector: for RAG vector storage (used by shield_engine.lightrag_adapter)
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # pgcrypto: for gen_random_uuid() (built-in PG13+, explicit for older PG)
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')

    # ---------- Tables (in FK dependency order) ----------
    op.execute('''
    
CREATE TABLE vapt_users (
	email VARCHAR(255) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	role VARCHAR(32) DEFAULT 'admin' NOT NULL, 
	display_name VARCHAR(255), 
	failed_login_attempts INTEGER DEFAULT '0' NOT NULL, 
	locked_until TIMESTAMP WITH TIME ZONE, 
	last_login_at TIMESTAMP WITH TIME ZONE, 
	settings JSONB DEFAULT '{}' NOT NULL, 
	is_active BOOLEAN DEFAULT 'true' NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_users PRIMARY KEY (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_refresh_tokens (
	user_id UUID NOT NULL, 
	token_hash VARCHAR(128) NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	revoked BOOLEAN DEFAULT 'false' NOT NULL, 
	revoked_at TIMESTAMP WITH TIME ZONE, 
	revoked_reason VARCHAR(255), 
	replaced_by_id UUID, 
	issued_from_ip VARCHAR(64), 
	issued_user_agent VARCHAR(512), 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_refresh_tokens PRIMARY KEY (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_scans (
	user_id UUID NOT NULL, 
	target TEXT NOT NULL, 
	target_type VARCHAR(32) NOT NULL, 
	agent_mode VARCHAR(32) DEFAULT 'supervisor' NOT NULL, 
	user_prompt TEXT, 
	parsed_intent JSONB, 
	status VARCHAR(32) DEFAULT 'pending' NOT NULL, 
	progress INTEGER DEFAULT '0' NOT NULL, 
	scope_json JSONB DEFAULT '{}' NOT NULL, 
	started_at TIMESTAMP WITHOUT TIME ZONE, 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	result_summary JSONB, 
	error TEXT, 
	id VARCHAR(64) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_scans PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_scans_user_id_vapt_users FOREIGN KEY(user_id) REFERENCES vapt_users (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_consent_forms (
	scan_id VARCHAR(64) NOT NULL, 
	asserted_owner VARCHAR(255) NOT NULL, 
	asserted_owner_role VARCHAR(64) NOT NULL, 
	declared_scope_json JSONB NOT NULL, 
	tos_accepted BOOLEAN NOT NULL, 
	tos_accepted_at TIMESTAMP WITHOUT TIME ZONE, 
	verification_method VARCHAR(32) NOT NULL, 
	verification_token VARCHAR(128), 
	verified BOOLEAN DEFAULT 'false' NOT NULL, 
	verified_at TIMESTAMP WITHOUT TIME ZONE, 
	verification_response TEXT, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_consent_forms PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_consent_forms_scan_id_vapt_scans FOREIGN KEY(scan_id) REFERENCES vapt_scans (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_assets (
	scan_id VARCHAR(64) NOT NULL, 
	type VARCHAR(32) NOT NULL, 
	value TEXT NOT NULL, 
	metadata_json JSONB DEFAULT '{}' NOT NULL, 
	discovered_by_agent VARCHAR(64), 
	confidence FLOAT DEFAULT '1.0' NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_assets PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_assets_scan_id_vapt_scans FOREIGN KEY(scan_id) REFERENCES vapt_scans (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_pentest_facts (
	scan_id VARCHAR(64) NOT NULL, 
	fact_type VARCHAR(32) NOT NULL, 
	fact_key VARCHAR(255) NOT NULL, 
	fact_value JSONB NOT NULL, 
	source_agent VARCHAR(64) NOT NULL, 
	confidence FLOAT DEFAULT '1.0' NOT NULL, 
	superseded_by_id UUID, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_pentest_facts PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_pentest_facts_scan_id_vapt_scans FOREIGN KEY(scan_id) REFERENCES vapt_scans (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_findings (
	scan_id VARCHAR(64) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	vuln_type VARCHAR(64) NOT NULL, 
	severity VARCHAR(16) NOT NULL, 
	cvss_vector VARCHAR(128), 
	cvss_base_score FLOAT, 
	cvss_severity VARCHAR(16), 
	location TEXT NOT NULL, 
	cwe_id VARCHAR(16), 
	cve_id VARCHAR(16), 
	wstg_test_id VARCHAR(32), 
	mitre_attack_technique VARCHAR(32), 
	mitre_attack_tactic VARCHAR(64), 
	mitre_attack_subtechnique VARCHAR(64), 
	poc_status VARCHAR(16) DEFAULT 'not_attempted' NOT NULL, 
	poc_tier INTEGER, 
	exploit_method VARCHAR(255), 
	shell_session_id UUID, 
	remediation TEXT, 
	verified BOOLEAN DEFAULT 'false' NOT NULL, 
	false_positive BOOLEAN DEFAULT 'false' NOT NULL, 
	auditor_verdict VARCHAR(32), 
	confidence_score FLOAT DEFAULT '0.0' NOT NULL, 
	metadata_json JSONB DEFAULT '{}' NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_findings PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_findings_scan_id_vapt_scans FOREIGN KEY(scan_id) REFERENCES vapt_scans (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_evidence (
	finding_id UUID NOT NULL, 
	layer VARCHAR(32) NOT NULL, 
	raw_output TEXT NOT NULL, 
	tool_used VARCHAR(64) NOT NULL, 
	custody_seal VARCHAR(128) NOT NULL, 
	evidence_hash VARCHAR(128) NOT NULL, 
	captured_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	spill_path TEXT, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_evidence PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_evidence_finding_id_vapt_findings FOREIGN KEY(finding_id) REFERENCES vapt_findings (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_poc_results (
	finding_id UUID NOT NULL, 
	poc_type VARCHAR(64) NOT NULL, 
	command TEXT NOT NULL, 
	output TEXT NOT NULL, 
	success BOOLEAN NOT NULL, 
	reproducibility_confirmed BOOLEAN DEFAULT 'false' NOT NULL, 
	validated_at TIMESTAMP WITHOUT TIME ZONE, 
	hitl_approval_id UUID, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_poc_results PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_poc_results_finding_id_vapt_findings FOREIGN KEY(finding_id) REFERENCES vapt_findings (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_c2_sessions (
	scan_id VARCHAR(64) NOT NULL, 
	beacon_type VARCHAR(32) NOT NULL, 
	listener_type VARCHAR(32) NOT NULL, 
	listener_id UUID, 
	remote_address VARCHAR(64) NOT NULL, 
	hostname VARCHAR(255), 
	username VARCHAR(255), 
	os VARCHAR(255), 
	arch VARCHAR(16), 
	checkin_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	last_seen_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	expires_at TIMESTAMP WITHOUT TIME ZONE, 
	status VARCHAR(16) DEFAULT 'active' NOT NULL, 
	metadata_json JSONB DEFAULT '{}' NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_c2_sessions PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_c2_sessions_scan_id_vapt_scans FOREIGN KEY(scan_id) REFERENCES vapt_scans (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_c2_tasks (
	session_id UUID NOT NULL, 
	command TEXT NOT NULL, 
	args_json JSONB NOT NULL, 
	level INTEGER NOT NULL, 
	hitl_approval_id UUID, 
	status VARCHAR(16) DEFAULT 'queued' NOT NULL, 
	result TEXT, 
	exit_code INTEGER, 
	sent_at TIMESTAMP WITHOUT TIME ZONE, 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	error TEXT, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_c2_tasks PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_c2_tasks_session_id_vapt_c2_sessions FOREIGN KEY(session_id) REFERENCES vapt_c2_sessions (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_hitl_approvals (
	scan_id VARCHAR(64) NOT NULL, 
	tool_name VARCHAR(64) NOT NULL, 
	target TEXT NOT NULL, 
	args_json JSONB NOT NULL, 
	predicted_impact VARCHAR(32) NOT NULL, 
	agent_reasoning TEXT NOT NULL, 
	kg_confidence FLOAT NOT NULL, 
	status VARCHAR(16) DEFAULT 'pending' NOT NULL, 
	user_decision VARCHAR(16), 
	edited_args_json JSONB, 
	time_limit_seconds INTEGER, 
	decided_at TIMESTAMP WITHOUT TIME ZONE, 
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	decided_by_user_id UUID, 
	result_table VARCHAR(64), 
	result_id UUID, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_hitl_approvals PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_hitl_approvals_scan_id_vapt_scans FOREIGN KEY(scan_id) REFERENCES vapt_scans (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_audit_log (
	actor_type VARCHAR(16) NOT NULL, 
	actor_id VARCHAR(64), 
	action VARCHAR(64) NOT NULL, 
	target_table VARCHAR(64), 
	target_id VARCHAR(64), 
	before_json JSONB, 
	after_json JSONB, 
	ip_address VARCHAR(64), 
	user_agent VARCHAR(512), 
	scan_id VARCHAR(64), 
	prev_seal VARCHAR(128), 
	tamper_seal VARCHAR(128) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	CONSTRAINT pk_vapt_audit_log PRIMARY KEY (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_quarantine (
	scan_id VARCHAR(64), 
	source VARCHAR(32) NOT NULL, 
	source_id VARCHAR(64), 
	reason VARCHAR(64) NOT NULL, 
	quarantined_content BYTEA NOT NULL, 
	original_hash VARCHAR(128) NOT NULL, 
	reviewed BOOLEAN DEFAULT 'false' NOT NULL, 
	reviewed_at TIMESTAMP WITHOUT TIME ZONE, 
	reviewed_by_user_id UUID, 
	review_decision VARCHAR(16), 
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_quarantine PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_quarantine_scan_id_vapt_scans FOREIGN KEY(scan_id) REFERENCES vapt_scans (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_attack_chains (
	scan_id VARCHAR(64) NOT NULL, 
	source_node_type VARCHAR(32) NOT NULL, 
	source_node_id VARCHAR(64) NOT NULL, 
	target_node_type VARCHAR(32) NOT NULL, 
	target_node_id VARCHAR(64) NOT NULL, 
	edge_type VARCHAR(32) NOT NULL, 
	metadata_json JSONB DEFAULT '{}' NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_attack_chains PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_attack_chains_scan_id_vapt_scans FOREIGN KEY(scan_id) REFERENCES vapt_scans (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_retest_requests (
	finding_id UUID NOT NULL, 
	scan_id VARCHAR(64) NOT NULL, 
	status VARCHAR(16) DEFAULT 'pending' NOT NULL, 
	scheduled_at TIMESTAMP WITHOUT TIME ZONE, 
	started_at TIMESTAMP WITHOUT TIME ZONE, 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	retest_scan_id VARCHAR(64), 
	retest_finding_id UUID, 
	user_comment TEXT, 
	disclosure_window_expires_at TIMESTAMP WITHOUT TIME ZONE, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_retest_requests PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_retest_requests_finding_id_vapt_findings FOREIGN KEY(finding_id) REFERENCES vapt_findings (id), 
	CONSTRAINT fk_vapt_retest_requests_scan_id_vapt_scans FOREIGN KEY(scan_id) REFERENCES vapt_scans (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_wstg_methodology_catalog (
	wstg_id VARCHAR(32) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	category VARCHAR(64) NOT NULL, 
	description TEXT, 
	related_mitre_attack JSONB DEFAULT '[]' NOT NULL, 
	related_cwe JSONB DEFAULT '[]' NOT NULL, 
	applicable_to_web_mvp BOOLEAN DEFAULT 'true' NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_wstg_methodology_catalog PRIMARY KEY (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_skill_executions (
	scan_id VARCHAR(64), 
	skill_name VARCHAR(128) NOT NULL, 
	agent_name VARCHAR(64) NOT NULL, 
	invoked_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	success BOOLEAN DEFAULT 'false' NOT NULL, 
	output_summary TEXT, 
	skill_version VARCHAR(32), 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_skill_executions PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_skill_executions_scan_id_vapt_scans FOREIGN KEY(scan_id) REFERENCES vapt_scans (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_kg_nodes (
	node_type VARCHAR(32) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	metadata_json JSONB DEFAULT '{}' NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_kg_nodes PRIMARY KEY (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_kg_edges (
	source_node_id UUID NOT NULL, 
	target_node_id UUID NOT NULL, 
	edge_type VARCHAR(32) NOT NULL, 
	success_count INTEGER DEFAULT '0' NOT NULL, 
	total_attempts INTEGER DEFAULT '0' NOT NULL, 
	probability FLOAT DEFAULT '0.5' NOT NULL, 
	wstg_test_id VARCHAR(32), 
	mitre_attack_technique VARCHAR(32), 
	last_scan_id VARCHAR(64), 
	metadata_json JSONB DEFAULT '{}' NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_kg_edges PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_kg_edges_source_node_id_vapt_kg_nodes FOREIGN KEY(source_node_id) REFERENCES vapt_kg_nodes (id), 
	CONSTRAINT fk_vapt_kg_edges_target_node_id_vapt_kg_nodes FOREIGN KEY(target_node_id) REFERENCES vapt_kg_nodes (id), 
	CONSTRAINT fk_vapt_kg_edges_last_scan_id_vapt_scans FOREIGN KEY(last_scan_id) REFERENCES vapt_scans (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_kg_scan_snapshots (
	scan_id VARCHAR(64) NOT NULL, 
	snapshot_json JSONB, 
	snapshot_path TEXT, 
	merge_status VARCHAR(16) DEFAULT 'pending' NOT NULL, 
	merged_at TIMESTAMP WITHOUT TIME ZONE, 
	node_count INTEGER NOT NULL, 
	edge_count INTEGER NOT NULL, 
	edges_updated INTEGER NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_kg_scan_snapshots PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_kg_scan_snapshots_scan_id_vapt_scans FOREIGN KEY(scan_id) REFERENCES vapt_scans (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_replay_traces (
	scan_id VARCHAR(64) NOT NULL, 
	trace_file_path TEXT NOT NULL, 
	turn_count INTEGER NOT NULL, 
	total_reward FLOAT NOT NULL, 
	start_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	end_timestamp TIMESTAMP WITHOUT TIME ZONE, 
	kg_edges_updated_json JSONB DEFAULT '[]' NOT NULL, 
	final_epsilon FLOAT, 
	final_q_values_json JSONB, 
	agent_mode VARCHAR(32), 
	scan_status VARCHAR(16), 
	notes TEXT, 
	pdf_export_path TEXT, 
	pdf_exported_at TIMESTAMP WITHOUT TIME ZONE, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_replay_traces PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_replay_traces_scan_id_vapt_scans FOREIGN KEY(scan_id) REFERENCES vapt_scans (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_rl_checkpoints (
	scan_id VARCHAR(64), 
	weights_blob BYTEA NOT NULL, 
	q_meta_json JSONB NOT NULL, 
	is_initial BOOLEAN DEFAULT 'false' NOT NULL, 
	weights_hash VARCHAR(128) NOT NULL, 
	adaptive_encoder_config JSONB, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_vapt_rl_checkpoints PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_rl_checkpoints_scan_id_vapt_scans FOREIGN KEY(scan_id) REFERENCES vapt_scans (id)
)


    ''')

    op.execute('''
    
CREATE TABLE vapt_rl_transitions (
	scan_id VARCHAR(64) NOT NULL, 
	turn INTEGER NOT NULL, 
	state_vector JSONB NOT NULL, 
	action INTEGER NOT NULL, 
	reward FLOAT NOT NULL, 
	next_state_vector JSONB NOT NULL, 
	done BOOLEAN NOT NULL, 
	priority FLOAT DEFAULT '1.0' NOT NULL, 
	td_error FLOAT, 
	action_name VARCHAR(64), 
	reward_breakdown JSONB, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	CONSTRAINT pk_vapt_rl_transitions PRIMARY KEY (id), 
	CONSTRAINT fk_vapt_rl_transitions_scan_id_vapt_scans FOREIGN KEY(scan_id) REFERENCES vapt_scans (id)
)


    ''')


    # ---------- Indexes ----------
    op.execute('CREATE UNIQUE INDEX ix_vapt_users_email ON vapt_users (email)')
    op.execute('CREATE UNIQUE INDEX ix_vapt_refresh_tokens_token_hash ON vapt_refresh_tokens (token_hash)')
    op.execute('CREATE INDEX ix_vapt_refresh_tokens_expires_at ON vapt_refresh_tokens (expires_at)')
    op.execute('CREATE INDEX ix_vapt_refresh_tokens_user_id ON vapt_refresh_tokens (user_id)')
    op.execute('CREATE INDEX ix_vapt_scans_user_id ON vapt_scans (user_id)')
    op.execute('CREATE INDEX ix_vapt_scans_status ON vapt_scans (status)')
    op.execute('CREATE INDEX ix_vapt_consent_forms_scan_id ON vapt_consent_forms (scan_id)')
    op.execute('CREATE INDEX ix_vapt_assets_value ON vapt_assets (value)')
    op.execute('CREATE INDEX ix_vapt_assets_type ON vapt_assets (type)')
    op.execute('CREATE INDEX ix_vapt_assets_scan_id ON vapt_assets (scan_id)')
    op.execute('CREATE INDEX ix_vapt_pentest_facts_fact_type ON vapt_pentest_facts (fact_type)')
    op.execute('CREATE INDEX ix_vapt_pentest_facts_fact_key ON vapt_pentest_facts (fact_key)')
    op.execute('CREATE INDEX ix_vapt_pentest_facts_scan_id ON vapt_pentest_facts (scan_id)')
    op.execute('CREATE INDEX ix_vapt_findings_cve_id ON vapt_findings (cve_id)')
    op.execute('CREATE INDEX ix_vapt_findings_scan_id ON vapt_findings (scan_id)')
    op.execute('CREATE INDEX ix_vapt_findings_severity ON vapt_findings (severity)')
    op.execute('CREATE INDEX ix_vapt_findings_vuln_type ON vapt_findings (vuln_type)')
    op.execute('CREATE INDEX ix_vapt_findings_mitre_attack_technique ON vapt_findings (mitre_attack_technique)')
    op.execute('CREATE INDEX ix_vapt_findings_cwe_id ON vapt_findings (cwe_id)')
    op.execute('CREATE INDEX ix_vapt_findings_wstg_test_id ON vapt_findings (wstg_test_id)')
    op.execute('CREATE INDEX ix_vapt_evidence_finding_id ON vapt_evidence (finding_id)')
    op.execute('CREATE INDEX ix_vapt_evidence_layer ON vapt_evidence (layer)')
    op.execute('CREATE INDEX ix_vapt_evidence_evidence_hash ON vapt_evidence (evidence_hash)')
    op.execute('CREATE INDEX ix_vapt_poc_results_finding_id ON vapt_poc_results (finding_id)')
    op.execute('CREATE INDEX ix_vapt_c2_sessions_scan_id ON vapt_c2_sessions (scan_id)')
    op.execute('CREATE INDEX ix_vapt_c2_sessions_beacon_type ON vapt_c2_sessions (beacon_type)')
    op.execute('CREATE INDEX ix_vapt_c2_sessions_remote_address ON vapt_c2_sessions (remote_address)')
    op.execute('CREATE INDEX ix_vapt_c2_sessions_status ON vapt_c2_sessions (status)')
    op.execute('CREATE INDEX ix_vapt_c2_tasks_status ON vapt_c2_tasks (status)')
    op.execute('CREATE INDEX ix_vapt_c2_tasks_session_id ON vapt_c2_tasks (session_id)')
    op.execute('CREATE INDEX ix_vapt_c2_tasks_level ON vapt_c2_tasks (level)')
    op.execute('CREATE INDEX ix_vapt_hitl_approvals_status ON vapt_hitl_approvals (status)')
    op.execute('CREATE INDEX ix_vapt_hitl_approvals_tool_name ON vapt_hitl_approvals (tool_name)')
    op.execute('CREATE INDEX ix_vapt_hitl_approvals_scan_id ON vapt_hitl_approvals (scan_id)')
    op.execute('CREATE INDEX ix_vapt_audit_log_actor_type ON vapt_audit_log (actor_type)')
    op.execute('CREATE INDEX ix_vapt_audit_log_target_table ON vapt_audit_log (target_table)')
    op.execute('CREATE INDEX ix_vapt_audit_log_actor_id ON vapt_audit_log (actor_id)')
    op.execute('CREATE INDEX ix_vapt_audit_log_created_at ON vapt_audit_log (created_at)')
    op.execute('CREATE INDEX ix_vapt_audit_log_action ON vapt_audit_log (action)')
    op.execute('CREATE INDEX ix_vapt_audit_log_scan_id ON vapt_audit_log (scan_id)')
    op.execute('CREATE INDEX ix_vapt_quarantine_scan_id ON vapt_quarantine (scan_id)')
    op.execute('CREATE INDEX ix_vapt_quarantine_expires_at ON vapt_quarantine (expires_at)')
    op.execute('CREATE INDEX ix_vapt_attack_chains_source_node_type ON vapt_attack_chains (source_node_type)')
    op.execute('CREATE INDEX ix_vapt_attack_chains_scan_id ON vapt_attack_chains (scan_id)')
    op.execute('CREATE INDEX ix_vapt_attack_chains_edge_type ON vapt_attack_chains (edge_type)')
    op.execute('CREATE INDEX ix_vapt_retest_requests_scan_id ON vapt_retest_requests (scan_id)')
    op.execute('CREATE INDEX ix_vapt_retest_requests_finding_id ON vapt_retest_requests (finding_id)')
    op.execute('CREATE INDEX ix_vapt_retest_requests_disclosure_window_expires_at ON vapt_retest_requests (disclosure_window_expires_at)')
    op.execute('CREATE INDEX ix_vapt_retest_requests_status ON vapt_retest_requests (status)')
    op.execute('CREATE UNIQUE INDEX ix_vapt_wstg_methodology_catalog_wstg_id ON vapt_wstg_methodology_catalog (wstg_id)')
    op.execute('CREATE INDEX ix_vapt_wstg_methodology_catalog_category ON vapt_wstg_methodology_catalog (category)')
    op.execute('CREATE INDEX ix_vapt_skill_executions_scan_id ON vapt_skill_executions (scan_id)')
    op.execute('CREATE INDEX ix_vapt_skill_executions_skill_name ON vapt_skill_executions (skill_name)')
    op.execute('CREATE INDEX ix_vapt_kg_nodes_node_type ON vapt_kg_nodes (node_type)')
    op.execute('CREATE INDEX ix_vapt_kg_nodes_name ON vapt_kg_nodes (name)')
    op.execute('CREATE INDEX ix_vapt_kg_edges_mitre_attack_technique ON vapt_kg_edges (mitre_attack_technique)')
    op.execute('CREATE INDEX ix_vapt_kg_edges_wstg_test_id ON vapt_kg_edges (wstg_test_id)')
    op.execute('CREATE INDEX ix_vapt_kg_edges_edge_type ON vapt_kg_edges (edge_type)')
    op.execute('CREATE INDEX ix_vapt_kg_edges_target_node_id ON vapt_kg_edges (target_node_id)')
    op.execute('CREATE INDEX ix_vapt_kg_edges_source_node_id ON vapt_kg_edges (source_node_id)')
    op.execute('CREATE INDEX ix_vapt_kg_scan_snapshots_scan_id ON vapt_kg_scan_snapshots (scan_id)')
    op.execute('CREATE INDEX ix_vapt_kg_scan_snapshots_merge_status ON vapt_kg_scan_snapshots (merge_status)')
    op.execute('CREATE INDEX ix_vapt_replay_traces_scan_status ON vapt_replay_traces (scan_status)')
    op.execute('CREATE UNIQUE INDEX ix_vapt_replay_traces_scan_id ON vapt_replay_traces (scan_id)')
    op.execute('CREATE INDEX ix_vapt_rl_checkpoints_scan_id ON vapt_rl_checkpoints (scan_id)')
    op.execute('CREATE INDEX ix_vapt_rl_transitions_priority ON vapt_rl_transitions (priority)')
    op.execute('CREATE INDEX ix_vapt_rl_transitions_created_at ON vapt_rl_transitions (created_at)')
    op.execute('CREATE INDEX ix_vapt_rl_transitions_scan_id ON vapt_rl_transitions (scan_id)')
    op.execute('CREATE INDEX ix_vapt_rl_transitions_turn ON vapt_rl_transitions (turn)')


def downgrade() -> None:
    # ---------- Drop tables in reverse FK order ----------
    op.execute('DROP TABLE IF EXISTS vapt_rl_transitions CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_rl_checkpoints CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_replay_traces CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_kg_scan_snapshots CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_kg_edges CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_kg_nodes CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_skill_executions CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_wstg_methodology_catalog CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_retest_requests CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_attack_chains CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_quarantine CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_audit_log CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_hitl_approvals CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_c2_tasks CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_c2_sessions CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_poc_results CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_evidence CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_findings CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_pentest_facts CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_assets CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_consent_forms CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_scans CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_refresh_tokens CASCADE')
    op.execute('DROP TABLE IF EXISTS vapt_users CASCADE')

    # NOTE: Do NOT drop extensions — they may be used by legacy EVVO tables
    # (e.g. embeddings column in knowledge_entries uses pgvector).
    # op.execute('DROP EXTENSION IF EXISTS vector')
    # op.execute('DROP EXTENSION IF EXISTS pgcrypto')
