"""
W1-E: Generate Alembic migration `0003_vapt_ai_baseline` from Base.metadata.

This script generates a complete Alembic migration file that creates all 24
VAPT-AI tables (18 W1-C + 6 W1-D) + pgvector + pgcrypto extensions.

Strategy:
    - Import Base + all models (registers tables with metadata)
    - Topologically sort tables by FK dependency (parents before children)
    - Use SQLAlchemy PostgreSQL dialect to generate DDL per table
    - Wrap DDL in Alembic op.execute() calls
    - Generate CREATE INDEX statements
    - Write complete migration file with upgrade()/downgrade() functions

Output:
    /home/nhat/VAPT-AI/alembic/versions/0003_vapt_ai_baseline.py

Usage:
    python3 /home/nhat/VAPT-AI/scripts/w1e_generate_migration.py
"""
from __future__ import annotations

import sys
from pathlib import Path
from datetime import datetime

# Ensure project root on sys.path
PROJECT_ROOT = Path("/home/nhat/VAPT-AI")
sys.path.insert(0, str(PROJECT_ROOT))

from sqlalchemy import create_mock_engine
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateTable, CreateIndex

from app.db.base import Base
# Import all models to register them with Base.metadata
from app.db.models import (  # noqa: F401
    User, RefreshToken,
    Scan, ConsentForm, Asset,
    PentestFact, Finding, Evidence, PoCResult,
    C2Session, C2Task,
    HITLApproval,
    AuditLog, Quarantine,
    AttackChain, RetestRequest,
    WSTGMethodologyCatalog, SkillExecution,
    RLCheckpoint, RLTransition,
    KGNode, KGEdge, KGScanSnapshot,
    ReplayTrace,
)


# ---------- Topological sort by FK dependency ----------

def topo_sort_tables(metadata) -> list[str]:
    """Sort table names so that parents come before children (FK order)."""
    tables = list(metadata.tables.values())
    sorted_names: list[str] = []
    visited: set[str] = set()
    visiting: set[str] = set()

    def visit(table):
        if table.name in visited:
            return
        if table.name in visiting:
            # Circular FK — defer (SQLAlchemy will create with ALTER TABLE ADD CONSTRAINT)
            return
        visiting.add(table.name)
        for fk in table.foreign_keys:
            parent_table = fk.column.table
            if parent_table.name != table.name:  # skip self-references
                visit(parent_table)
        visiting.discard(table.name)
        visited.add(table.name)
        sorted_names.append(table.name)

    for t in tables:
        visit(t)

    # Add any tables not visited (shouldn't happen, but safety)
    for t in tables:
        if t.name not in visited:
            sorted_names.append(t.name)

    return sorted_names


# ---------- DDL generation ----------

def generate_table_ddl(table, dialect) -> str:
    """Generate CREATE TABLE DDL for a single table."""
    return str(CreateTable(table).compile(dialect=dialect))


def generate_index_ddl(table, dialect) -> list[str]:
    """Generate CREATE INDEX DDL for all indexes on a table."""
    stmts = []
    for index in table.indexes:
        stmts.append(str(CreateIndex(index).compile(dialect=dialect)))
    return stmts


# ---------- Migration file generation ----------

MIGRATION_TEMPLATE = '''"""VAPT-AI v3.2 baseline — 24 new tables (18 W1-C + 6 W1-D)

Creates all VAPT-AI-specific tables (prefixed with vapt_) + pgvector + pgcrypto
extensions. Does NOT touch legacy EVVO tables (users, scans, findings, ...)
which are still in use by 482 tests — those are filtered out by alembic/env.py
include_object().

Tables created (in FK dependency order):
{table_list}

Extensions:
    - pgvector (for RAG / LightRAG vector storage)
    - pgcrypto (for gen_random_uuid() — built-in PG13+, but explicit for safety)

Revision ID: 0003_vapt_ai_baseline
Revises: 0002
Create Date: {create_date}

Generated by: /home/z/my-project/scripts/w1e_generate_migration.py
DO NOT EDIT MANUALLY — regenerate from models if schema changes.
"""
from __future__ import annotations

from alembic import op


revision = "0003_vapt_ai_baseline"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ---------- Extensions ----------
    # pgvector: for RAG vector storage (used by shield_engine.lightrag_adapter)
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # pgcrypto: for gen_random_uuid() (built-in PG13+, explicit for older PG)
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')

    # ---------- Tables (in FK dependency order) ----------
{upgrade_stmts}

    # ---------- Indexes ----------
{index_stmts}


def downgrade() -> None:
    # ---------- Drop tables in reverse FK order ----------
{downgrade_stmts}

    # NOTE: Do NOT drop extensions — they may be used by legacy EVVO tables
    # (e.g. embeddings column in knowledge_entries uses pgvector).
    # op.execute('DROP EXTENSION IF EXISTS vector')
    # op.execute('DROP EXTENSION IF EXISTS pgcrypto')
'''


def generate_migration():
    dialect = postgresql.dialect()
    metadata = Base.metadata

    table_names = topo_sort_tables(metadata)
    print(f"Table creation order ({len(table_names)} tables):")
    for i, name in enumerate(table_names, 1):
        print(f"  {i:2d}. {name}")

    # Generate CREATE TABLE statements
    upgrade_lines = []
    index_lines = []
    for name in table_names:
        table = metadata.tables[name]
        ddl = generate_table_ddl(table, dialect)
        # Format: op.execute('''<DDL>''')
        upgrade_lines.append(f"    op.execute('''")
        upgrade_lines.append(f"    {ddl}")
        upgrade_lines.append(f"    ''')")
        upgrade_lines.append("")

        # Indexes
        for idx_ddl in generate_index_ddl(table, dialect):
            index_lines.append(f"    op.execute('{idx_ddl}')")

    # Generate DROP TABLE statements (reverse order)
    downgrade_lines = []
    for name in reversed(table_names):
        downgrade_lines.append(f"    op.execute('DROP TABLE IF EXISTS {name} CASCADE')")

    # Table list for docstring
    table_list = "\n".join(f"    {i:2d}. {name}" for i, name in enumerate(table_names, 1))

    # Build migration file
    migration_content = MIGRATION_TEMPLATE.format(
        table_list=table_list,
        create_date=datetime.now().strftime("%Y-%m-%d"),
        upgrade_stmts="\n".join(upgrade_lines),
        index_stmts="\n".join(index_lines) if index_lines else "    # (no explicit indexes — all via column index=True)",
        downgrade_stmts="\n".join(downgrade_lines),
    )

    # Write file
    output_path = PROJECT_ROOT / "alembic" / "versions" / "0003_vapt_ai_baseline.py"
    output_path.write_text(migration_content, encoding="utf-8")
    print(f"\n✓ Migration written: {output_path}")
    print(f"  Size: {output_path.stat().st_size} bytes")
    print(f"  Lines: {len(migration_content.splitlines())}")

    # Verify it compiles
    import py_compile
    py_compile.compile(str(output_path), doraise=True)
    print(f"  Compiles: OK")


if __name__ == "__main__":
    generate_migration()