"""
VAPT-AI Specialist Agents — W10-S4.

13 sub-agent classes (one per non-orchestrator agent in app/agents/*.md).
Each class inherits from app.agents.base.BaseAgent.

Generated by scripts/w10s4_generate_specialist_classes.py.
"""
from __future__ import annotations

from app.agents.specialists.engagement_planning_agent import EngagementPlanningAgent
from app.agents.specialists.intel_collection_agent import IntelCollectionAgent
from app.agents.specialists.recon_agent import ReconAgent
from app.agents.specialists.attack_surface_enumeration_agent import AttackSurfaceEnumerationAgent
from app.agents.specialists.vulnerability_triage_agent import VulnerabilityTriageAgent
from app.agents.specialists.penetration_agent import PenetrationAgent
from app.agents.specialists.privilege_escalation_agent import PrivilegeEscalationAgent
from app.agents.specialists.lateral_movement_agent import LateralMovementAgent
from app.agents.specialists.persistence_maintenance_agent import PersistenceMaintenanceAgent
from app.agents.specialists.impact_exfiltration_agent import ImpactExfiltrationAgent
from app.agents.specialists.opsec_evasion_agent import OpsecEvasionAgent
from app.agents.specialists.cleanup_rollback_agent import CleanupRollbackAgent
from app.agents.specialists.reporting_remediation_agent import ReportingRemediationAgent


__all__ = [
    "EngagementPlanningAgent",
    "IntelCollectionAgent",
    "ReconAgent",
    "AttackSurfaceEnumerationAgent",
    "VulnerabilityTriageAgent",
    "PenetrationAgent",
    "PrivilegeEscalationAgent",
    "LateralMovementAgent",
    "PersistenceMaintenanceAgent",
    "ImpactExfiltrationAgent",
    "OpsecEvasionAgent",
    "CleanupRollbackAgent",
    "ReportingRemediationAgent",
]
